### ISSUE TITLE
Getting null object reference on org.whispersystems.libsignal.state.SessionRecord.getSessionState()

### ISSUE THREAD

**Issue by jeeva-sil** [WhisperSystems/libsignal-protocol-java#30]
**Platform :** Android

**Java class :** SessionCipherTest.java (libsignal-protocol-java/tests/src/test/java/org/whispersystems/libsignal/SessionCipherTest.java).

**Issues :** `java.lang.NullPointerException`

While executing class getting error in the line 
` CiphertextMessage message        = aliceCipher.encrypt(alicePlaintext);`

**Error shows as :**

```
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'org.whispersystems.libsignal.state.SessionState org.whispersystems.libsignal.state.SessionRecord.getSessionState()' on a null object reference

W/System.err:     at org.whispersystems.libsignal.SessionCipher.encrypt(SessionCipher.java:104)

W/System.err:     at com.kasbah.hugarro.signaljavalibtest.MainActivity.runInteraction(MainActivity.java:203)

W/System.err:     at com.kasbah.hugarro.signaljavalibtest.MainActivity.testBasicSessionV3(MainActivity.java:138)

 W/System.err:     at com.kasbah.hugarro.signaljavalibtest.MainActivity.onCreate(MainActivity.java:109)

W/System.err:     at android.app.Activity.performCreate(Activity.java:6010)

W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)

W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)

W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)

W/System.err:     at android.app.ActivityThread.access$800(ActivityThread.java:155)

W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)

W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)

W/System.err:     at android.os.Looper.loop(Looper.java:135)

W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5343)

W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)

W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```

What is the problem and how to solve this.

**Comment by moxie0** [comment]
Hey @jeeva-sil it looks like you're having problems with some of your own code rather than something in this repo.  Sorry, but we don't use this issue tracker as a discussion forum. You might have better luck on dedicated forums.
